GEMINI_API_KEY=AIzaSyDov0k-eA9ZR1E6TIIiHD2SLf6mShpB8NI
GROQ_API_KEY =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

DB_HOST=ep-broad-bush-a5xjz0wm-pooler.us-east-2.aws.neon.tech
DB_NAME=neondb
DB_USER=neondb_owner
DB_PASSWORD=npg_LgZ4en1QpsyD
DB_PORT=5432

MONGO_USER=Raj
MONGO_PASS=oll@1333
MONGO_CLUSTER=taskmanager.h5obfpt.mongodb.net
MONGO_DB=discussions_db
MONGO_APP=Taskmanager
